# Generated by Django 4.2.5 on 2023-09-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderName', models.CharField(max_length=30)),
                ('SenderAddress', models.CharField(max_length=30)),
                ('SenderPhone', models.CharField(max_length=30)),
                ('receiverName', models.CharField(max_length=30)),
                ('receiverAddress', models.CharField(max_length=30)),
                ('receiverPhone', models.CharField(max_length=30)),
                ('waybillno', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('payment_way', models.CharField(choices=[('CASH', 'CASH'), ('COD', 'COD')], default='CASH', max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
