# Generated by Django 4.2.5 on 2023-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='waybillno',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
