# Generated by Django 4.2.3 on 2023-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_orders_waybillno"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="curr_location",
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="receiverAddress2",
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
